server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres?user=postgres.vncvvgiohvexjkwtfbaf&password=Sanket@123.com
    username: postgres
    password: Sanket@123.com
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true