server:
  port: 8080

spring:
  datasource:
    url: dburl
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

jwt:
  secret-key: jwt secret key
  access-token-expiration: 900000  #15min
  refresh-token-expiration: 604800000  #7days

cloudinary:
  cloud-name: cloud name
  api-key: api key
  api-secret: api secret